#! /bin/zsh

path+=('/usr/local/scripts')
path+=('/usr/local/scripts/tikz2svg-master')
path+=('/usr/local/Cellar/gcc@7')
path+=('/usr/local/opt/python/libexec/bin')
# path+=('$HOME/.cargo.bin')

# ruby stuff
# eval "$(rbenv init -)"
# if which ruby >/dev/null && which gem >/dev/null; then
#     PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
# fi

# gem stuff
# export GEM_HOME="$HOME/.gem"
# export GEM_PATH="$HOME/.gem"
