#! /bin/zsh

function ed() {
  case $1 in
  '.') $VIM $ZSH_DOTS/brew/edits;;
  'g'|'git') $VIM $HOME/.gitconfig;;
  'v'|'nvim') $VIM $REPOS/neovim/init.lua;;
  'vm') $VIM $REPOS/neovim/plugged/vim-markdown/syntax/markdown.vim;;
  'z'|'zsh') $VIM $REPOS/zsh/zshrc;;
  *) echo "nothing happened.";;
  esac
}
