#! /bin/zsh

SV="192.168.1.9"
function 2s() {
  echo "brew@192.168.1.9"
  ssh brew@192.168.1.9
}

SYNCED_DIR="$HOME/server/"

function wd() {
  case $1 in
  "up")
    rsync -a $SYNCED_DIR brew@$SV:~/files;;
  "down")
    rsync -a brew@$SV:~/files/ $SYNCED_DIR;;
  *) echo "nothing happened.";;
  esac
}
