#! /bin/zsh

function mk() {
  M=$PWD
  cd $REPOS/qmk_firmware && make keebio/iris/rev4:khang
  cd $M && unset M
}

function mkd() {
  M=$PWD
  cd $REPOS/qmk_firmware && make keebio/iris/rev4:khang:flash
  cd $M && unset M
}
