#! /bin/zsh

alias out="cd .."
alias back="cd -"

# doc_start
alias rep="cd $REPOS"
alias 2.="$VIM $REPOS/zsh/brew/nav"
alias 2a="cd $REPOS/arch"
alias 2ap="cd $REPOS/arch/packages"
alias 2asc="cd $AS/.config"
alias 2ase="cd $AS/etc"
alias 2asl="cd $REPOS/arch/scripts/local-bin"
alias 2b="cd $REPOS/blog/data"
alias 2bs="cd $REPOS/blog/data/snippets"
alias 2bb="cd $REPOS/blog/data/blog"
alias 2c="cd $HOME/.config"
alias 2d="cd $HOME/Downloads"
alias 2g="cd /Volumes/Gauss"
alias 2f="cd $HOME/files"
alias 2h="cd $REPOS/hcanoe-telegram/repo"
alias 2hw="cd $REPOS/hcanoe-telegram/wiki"
alias h2="cd $REPOS/n3"
alias 2hs="cd $HOME/server"
alias 2l="cd $HOME/.local"
alias 2ls="cd $HOME/.local/src"
alias 2lsf="cd $HOME/.local/share/fonts"
alias 2lb="cd $HOME/.local/bin"
alias 2i="cd $REPOS/ai"
alias 2m="cd $REPOS/minecraft"
alias 2n="cd $REPOS/notes"
alias 2pw="cd $REPOS/p"
alias 2p="cd $REPOS/neovim/plugged"
alias 2pr="cd $HOME/files/primeagen_dots/nvim/.config/nvim"
alias 2k="cd $REPOS/arch/settings/keymap"
alias 2q="cd $REPOS/qmk_firmware"
alias 2t="cd $AS/.config/kitty"
alias 2tel="cd $HOME/.config/nvim/plugged/telescope.nvim/lua/telescope"
alias 2t.="cd $HOME/.config/kitty"
alias 2v="cd $REPOS/neovim"
alias 2v.="cd $HOME/.config/nvim"
alias 2vs="cd $REPOS/neovim/sessions"
alias 2w="cd $REPOS/blog/data/blog"
alias 2z="cd $ZSH_DOTS"
# doc_end

function 2,() {
  cat $ZSH_DOTS/brew/nav \
    | sed -n '/^# doc_start/,/^# doc_end/{p;/^# doc_end/q}' \
    | sed 's/alias //g' \
    | head -n -1 \
    | tail -n +2
}

function 2r() {
  cd $(git rev-parse --show-toplevel)
}

function 2u() {
  BASEDIR="$REPOS/uni/nightly/modules/"
  MODS=$(fd \
    -t d \
    -d 1 \
    --base-directory $BASEDIR \
    --exec basename)
  RES+="home\n$MODS"
  TARGET=$(echo $RES | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')

  case $TARGET in 
    "")
      unset RES TARGET MODS
      return true;;
    "home") cd $BASEDIR..;;
    *) cd $BASEDIR$TARGET;;
  esac
  unset RES TARGET MODS
}


function g() {
  res=$(fd -t d --hidden)
  if [[ ${#res[@]} = 0 ]] then
    echo 'no children directories.'
    return
  fi
  target=$(echo $res | fzf --height=10 +m --no-mouse --reverse --no-info --prompt="  " --color='pointer:2')
  [[ ${#target} = 0 ]] && return true
  cd $target
}
