#! /bin/zsh

alias out="cd .."
alias back="cd -"

alias rep="cd $REPOS"
alias 2.="nvim $REPOS/zsh/brew/nav"
alias 2a="cd $REPOS/arch"
alias 2ap="cd $REPOS/arch/packages"
alias 2asc="cd $AS/.config"
alias 2ase="cd $AS/etc"
alias 2asl="cd $REPOS/arch/scripts/local-bin"
alias 2b="cd $REPOS/blog/data"
alias 2bs="cd $REPOS/blog/data/snippets"
alias 2bb="cd $REPOS/blog/data/blog"
alias 2c="cd $HOME/.config"
alias 2d="cd $REPOS/dwm"
alias 2g="cd /run/media/khang/Gauss"
alias 2h="cd $REPOS/hcanoe"
alias 2hs="cd $HOME/server"
alias 2ls="cd $HOME/.local/share"
alias 2lsf="cd $HOME/.local/share/fonts"
alias 2lb="cd $HOME/.local/bin"
alias 2i="cd $REPOS/ai"
alias 2n="cd $REPOS/notes"
alias 2p="cd $REPOS/p"
alias 2pr="cd $HOME/files/primeagen_dots/nvim/.config/nvim"
alias 2k="cd $REPOS/qmk_firmware/keyboards/keebio/iris/keymaps"
alias 2q="cd $REPOS/qmk_firmware"
alias 2t="cd $AS/.config/kitty"
alias 2tel="cd $HOME/.config/nvim/plugged/telescope.nvim/lua/telescope"
alias 2t.="cd $HOME/.config/kitty"
alias 2uw="cd $REPOS/uni/nightly/website"
alias 2v="cd $REPOS/neovim"
alias 2v.="cd $HOME/.config/nvim"
alias 2vs="cd $REPOS/neovim/sessions"
alias 2w="cd $REPOS/blog/data/blog"
alias 2z="cd $REPOS/zsh"

function 2r() {
  cd $(git rev-parse --show-toplevel)
}

function 2u() {
  BASEDIR="$REPOS/uni/nightly/modules/"
  MODS=$(fd -t d -d 1 --base-directory $BASEDIR)
  RES+="home\n$MODS"
  TARGET=$(echo $RES | fzf --height=10 +m --no-mouse --reverse --no-info --prompt="  " --color='pointer:2')

  case $TARGET in 
    "")
      unset RES TARGET MODS
      return true;;
    "home") cd $BASEDIR..;;
    *) cd $BASEDIR$TARGET;;
  esac
  unset RES TARGET MODS
}
