#! /bin/zsh

NOTES="$REPOS/notes"
TODO_DIR="$REPOS/uni/nightly"
TODO_FILE="todo.md"

alias n="$VIM $NOTES/posts/.inbox.md"
alias t="$VIM $TODO_DIR/$TODO_FILE"

function vf() {
  q=$(fd --type file --no-ignore | fzf)
  [[ -z $q ]] && return
  vim $q
}
