#! /bin/zsh

# aliases
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias gup="pass git push"
alias ka="killall"
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias oc="octave"
alias py="python3"
alias yb="yarn build"
alias yd="yarn dev"
alias zr="exec $SHELL -l" # reloads shell
alias snus="ssh-copy-id kevincjk@stu.comp.nus.edu.sg"
alias 2030n="cd $ONE_NUS/Modules/CS2030S/notes; git pull origin; mkdocs serve"

# keybinds
bindkey "^[[3~" delete-char
bindkey '^[[Z' reverse-menu-complete

# options
unsetopt BEEP
