#! /bin/zsh

alias gup="pass git push"
alias zr="exec $SHELL -l"
alias z="zathura"
alias oc="octave"
alias yd="yarn dev"
alias yb="yarn build"
alias i="$VIM $REPOS/blog/data/ideas"
alias gcal="gcalcli"
