" run all .vim files in nvim folder
for f in split(glob('$ZSH_DOTS/brew/nvim/*.vim'), '\n')
    exe 'source' f
endfor

" run all .lua files in nvim folder
for f in split(glob('$ZSH_DOTS/brew/nvim/*.lua'), '\n')
    exe 'source' f
endfor
