#! /usr/bin/python

import datetime

blue = '\033[94m'
green = '\033[92m'
back = '\033[0m'

# read from `history`
def getHistory(file):
    f = open(file, 'r')
    lines = f.read().splitlines()
    f.close()
    return lines

# write to csv file
def writeCsv(file, contents):
    f = open(file, 'w')
    f.writelines(contents)
    f.close()

# prettify raw data from history file
def prettify(raw):
    d = {}
    csv = ['Time, Command\n']
    for i in raw:
        print(i)
        sse = int(i[1]) # seconds since epoch
        ts = str(datetime.datetime.utcfromtimestamp(sse))
        cmd = i[2].split(';')[1]

        if cmd in d:
            d[cmd].append(ts)
        else:
            d[cmd] = [ts]
        csv.append(ts + ', ' + cmd + '\n')
    return d, csv

def listify(d):
    l = [[x, len(d[x])] for x in d.keys()]
    l = sorted(l, key=lambda x: x[1])
    # l.reverse()
    return l

history = [x.split(':') for x in getHistory('history')]
d, csv = prettify(history)
l = listify(d)
writeCsv('commands.csv', csv)

for i in l:
    print(green + str(i[1]) + " " + back + i[0])
