#! /bin/zsh 
alias cdisp="xrandr --output HDMI1 --above eDP1 --mode 1920x1080 && ~/.fehbg && xmonad --restart"
alias arch="cd $REPOS/arch"
alias xedit="nvim ~/.xinitrc"
function eventviewer() {
     xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

#  ----------
# | MOUNTING |
#  ----------
function mountthe() {
    sudo mkdir -p /mnt/$2
    sudo mount $1 /mnt/$2 -o umask=000
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
}
function umountthe() {
    sudo umount /mnt/$1
    sudo rmdir /mnt/$1
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
}
function listmounted() {
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
}

#  -----
# | DWM |
#  -----
alias dwmm="cd $REPOS/dwm && rm -f config.h && make && sudo make install clean"
alias 2dwm="cd $REPOS/dwm"
alias ldwm="startx"
alias lnrd="cd $REPOS/dwm && rm -f config.h && make && sudo make install clean && cd ~ && startx"
alias dedit="nvim -S ~/.config/nvim/sessions/dwm"
