#! /bin/zsh 
alias cdisp="xrandr --output HDMI1 --above eDP1 --mode 1920x1080 && ~/.fehbg && xmonad --restart"
alias arch="cd $REPOS/arch"
alias xedit="nvim ~/.xinitrc"
function eventviewer() {
     xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

#  ----------
# | MOUNTING |
#  ----------
function mountblue() {
    s=$(sudo fdisk -l | awk 'c&&!--c;/My Passport 0820/{c=8}')
    prefix="/dev/"
    s=${s#"$prefix"}
    s=${s%% *}
    echo $s
    sudo mount /dev/$s /mnt/blue
}
function umountblue() {
    sudo umount /mnt/blue
}
alias 2blue="cd /mnt/blue"

#  -----
# | DWM |
#  -----
alias dwmm="cd $REPOS/dwm && rm -f config.h && make && sudo make install clean"
alias 2dwm="cd $REPOS/dwm"
alias ldwm="startx"
alias lnrd="cd $REPOS/dwm && rm -f config.h && make && sudo make install clean && cd ~ && startx"
alias dedit="nvim -S ~/.config/nvim/sessions/dwm"
