#! /bin/zsh 

alias 2code="cd $REPOS/codeforces && rmdir --ignore-fail-on-non-empty */"
function 2today() {
    t=$(date +%Y-%m-%d)
    cd $REPOS/codeforces && rmdir --ignore-fail-on-non-empty */
    mkdir -p $t
    cd $t
}

# compile and run c++
function cnr() {
    echo ------------
    echo compiling...
    input="$*"
    g++ $input
    echo running:
    echo ------------
    time (cnr_run $*)
    rm a.out
}
function cnr_run() {
    input="$*"
    n=${input%.*}
    ./a.out < input_$n.txt
}

# run python    
function pnr() {
    input="$*"
    n=${input%.*}
    time (python3 $n.py < input_$n.txt)
}

# USAGE: problemset [difficulty]
function problemset() {
    diff=$1
    url="https://codeforces.com/problemset?tags="$diff"-"$diff
    firefox $url
}
