#! /bin/zsh

function edit() {
    case $1 in
        'this')
            nvim $ARCH_HOME/.config/zsh/dotfiles/edits;;
        'dwm')
            nvim $REPOS/dwm/config.def.h;;
        'spotifyd')
            nvim $ARCH_HOME/.config/spotifyd/spotifyd.conf;;
        'imwheel')
            nvim $ARCH_DOTS/.imwheelrc;;
        'spotify-tui')
            if [ "$2" = "c" ]; then
                nvim $ARCH_HOME/.config/spotify-tui/client.yml
            else
                nvim $ARCH_HOME/.config/spotify-tui/config.yml
            fi;;
        'rofi')
            nvim $ARCH_HOME/.config/rofi/config.rasi;;
        'xmobar')
            nvim $ARCH_DOTS/.xmobarrc;;
        'xmonad')
            nvim $ARCH_HOME/.xmonad/xmonad.hs;;
        'nvim')
            nvim $ARCH_HOME/.config/nvim/init.vim;;
        'dunst')
            nvim $ARCH_HOME/.config/dunst/dunstrc;;
        'kitty')
            nvim $ARCH_HOME/.config/kitty/kitty.conf;;
        'lsd')
            nvim $ARCH_HOME/.config/lsd/config.yaml;;
        'git')
            nvim $ARCH_DOTS/.xmobarrc;;
        'picom')
            nvim $ARCH_HOME/.config/picom/picom.conf;;
        'keeb')
            cd $REPOS/qmk_firmware
            nvim $REPOS/qmk_firmware/keyboards/dz60/keymaps/khang/keymap.c;;
        *) echo "nothing happened.";;
    esac
}
alias redit="nvim ~/.config/ranger/rifle.conf"
alias vedit="nvim ~/.config/nvim/init.vim"
alias tedit="nvim ~/.config/kitty/kitty.conf" # t for terminal
alias ledit="nvim ~/.config/lsd/config.yaml" # ls, ll, la manager
