#! /bin/zsh

function ed() {
    case $1 in
        '.')
            nvim $ZSH_DOTS/edits;;
        'dwmblocks'|'b') # bar
            nvim $REPOS/dwmblocks/blocks.def.h;;
        'dwm'|'d')
            nvim -S ~/.config/nvim/sessions/dwm;;
        'imwheel'|'i')
            nvim $REPOS/arch/settings/dotfiles/.imwheelrc;;
        'git'|'g')
            nvim $HOME/.gitconfig;;
        'keeb'|'k')
            cd $REPOS/qmk_firmware && nvim keyboards/dz60/keymaps/khang/keymap.c;;
        'lsd'|'l')
            nvim $REPOS/arch/settings/.config/lsd/config.yaml;;
        'dunst'|'n') # notifications
            nvim $REPOS/arch/settings/.config/dunst/dunstrc;;
        'picom'|'p')
            nvim $REPOS/arch/settings/.config/picom/picom.conf;;
        'rofi'|'r')
            nvim $REPOS/arch/settings/.config/rofi/config.rasi;;
        'kitty'|'t') # terminal
            nvim $REPOS/arch/settings/.config/kitty/kitty.conf;;
        'nvim'|'v') # vim
            nvim $REPOS/vim/init.vim;;
        'xinit'|'x')
            nvim $REPOS/arch/settings/dotfiles/.xinitrc;;
        'zsh'|'z')
            nvim $REPOS/zsh;;
        'zsh'|'zz') # zsh's zshrc + all files in that dir, depth=1
            nvim $REPOS/zsh/zshrc $REPOS/zsh/*(.);;
        *) echo "nothing happened.";;
    esac
}
