#! /bin/zsh

function ed() {
  case $1 in
  '.')
    $VIM $ZSH_DOTS/edits;;
  'alacritty'|'al') # bar
    $VIM $HOME/.config/alacritty/alacritty.yml;;
  'awesome'|'a') # bar
    $VIM $HOME/.config/awesome/rc.lua;;
  'dwmblocks'|'b') # bar
    $VIM $REPOS/dwm/dwmblocks/blocks.def.h;;
  'dwm'|'d')
    $VIM $REPOS/dwm/config.def.h;;
  'dwm'|'do')
    $VIM $REPOS/dwm-old/config.def.h;;
  'dwm'|'dc')
    $VIM $REPOS/dwm/dwm.c;;
  'dunst')
    $VIM ~/.config/dunst/dunstrc;;
  'imwheel'|'im')
    $VIM $REPOS/arch/settings/dotfiles/.imwheelrc;;
  'i3'|'i')
    $VIM $HOME/.config/i3/config;;
  'firefox'|'f')
    $VIM $HOME/.mozilla/firefox/eg18esvc.default-release/chrome/userChrome.css;;
  'font'|'fo')
    sudo $VIM $HOME/.config/fontconfig/conf.d/50-user.conf;;
  'git'|'g')
    $VIM $HOME/.gitconfig;;
  'hosts'|'h')
    $VIM $REPOS/arch/settings/etc/hosts;;
  'keeb'|'k')
    cd $REPOS/qmk_firmware && $VIM keyboards/keebio/iris/keymaps/khang/keymap.c;;
  'lsd'|'l')
    $VIM $REPOS/arch/settings/.config/lsd/config.yaml;;
  'navigation'|'n')
    $VIM $REPOS/zsh/alias/nav;;
  'picom'|'p')
    $VIM $REPOS/arch/settings/.config/picom/picom.conf;;
  'rofi'|'r')
    $VIM $REPOS/arch/settings/.config/rofi/config.rasi;;
  'split'|'s')
    $VIM $REPOS/qmk_firmware/keyboards/keebio/iris/keymaps/khang/keymap.c;;
  'kitty'|'t') # terminal
    $VIM $REPOS/arch/settings/.config/kitty/kitty.conf;;
  'ueli'|'u')
    $VIM $HOME/Library/Application\ Support/ueli/config.json;;
  'nvim'|'v')
    $VIM $REPOS/neovim/init.vim;;
  'nvimlua'|'vl')
    $VIM $REPOS/neovim/lua/brew/init.lua;;
  'vim')
    $VIM $REPOS/neovim/vimrc;;
  'vs')
    $VIM $REPOS/neovim/sets.vim;;
  'vc')
    $VIM $REPOS/neovim/onedark.colorway.vim;;
  'xinit'|'x')
    $VIM $REPOS/arch/settings/dotfiles/.xinitrc;;
  'xmonad'|'xm')
    $VIM $HOME/.xmonad/xmonad.hs;;
  'xmobar'|'xb')
    $VIM $HOME/.xmobarrc;;
  'yabai'|'y')
    $VIM ~/.config/yabai/yabairc;;
  'zsh'|'z')
    $VIM $REPOS/zsh/zshrc;;
  'zshrc'|'zp') 
    $VIM $REPOS/zsh/prompt;;
  *) echo "nothing happened.";;
  esac
}
