#! /bin/zsh 

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=$VIM
export MANPAGER="$VIM -c 'set ft=man' -"

# for init.vim sourcing to bite onto
export VCONF="$HOME/.config/nvim"

# for alacritty DPI settings
export WINIT_X11_SCALE_FACTOR=1
export VIMTEX_OUTPUT_DIRECTORY=~/.tex
