#! /bin/zsh 

MATH="$REPOS/n3"

alias gh="$VIM $HOME/files/gnuplots/documentation"
function gnp() {
    [ -f settings.gp ] || (echo "no settings.gp file" && return 1) &&
    gnuplot -e "filename='$1'; load 'settings.gp'" $1
}
function h() {
	cd $MATH
	$VIM -S ~/.config/nvim/sessions/h
}
function h2() {
    cd $MATH
    [ "$1" ] && if [ -z "${1//[0-9]}" ]; then
        open=()
        for i in $@:
            if [[ $i = *":" ]]; then
                open+=("pages/ch${i%%:*}.mdx")
            else
                open+=("pages/ch$i.mdx")
            fi
        $VIM $open
        return
    fi
    case $1 in
        's')
            $VIM $MATH/public/style.css;;
        'a')
            $VIM $MATH/pages/_app.js;;
        'd')
            $VIM $MATH/pages/_document.js;;
        'i')
            $VIM $MATH/pages/index.mdx;;
        'm')
            $VIM $MATH/public/mathjax-config.js;;
        'v')
            $VIM -S ~/.config/nvim/sessions/math;;
        'pr')
            npx prettier --write -- pages components;;
        'p')
            cd $MATH/pages;;
        'g')
            cd $MATH/components/plots;;
        'n')
            cd $MATH/node_modules/nextra-theme-docs;;
        'r')
            cd $MATH && yarn dev;;
        '.')
            $VIM $REPOS/zsh/math -c "/function h2";;
        '');;
        *)
            echo "nothing happened.";;
    esac
}
alias debug="$VIM -S ~/.config/nvim/sessions/debug"

# old tikz to svg functions
function ttikz() {
    time (tikz $1)
}
function tikz() {
    x=$1
    if [[ $x =~ ^[0-9]\.[0-9]*$ ]]; then
        x=$(find . -name $x*)
        x=${${x:2}%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    elif [[ $x == *"tex" ]]; then
        x=${x%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    fi
}
