#! /bin/zsh 
alias 2math="cd $REPOS/math"
alias 2write="cd $REPOS/math/web/stage-1"
alias write="nvim -S ~/.config/nvim/sessions/math"
alias nwrite="cd $REPOS/n3/pages && nvim meta.json ch*"
function ttikz() {
    time (tikz $1)
}
function tikz() {
    x=$1
    if [[ $x =~ ^[0-9]\.[0-9]*$ ]]; then
        x=$(find . -name $x*)
        x=${${x:2}%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    elif [[ $x == *"tex" ]]; then
        x=${x%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    fi
}
