#! /bin/zsh 

alias gh="nvim $HOME/files/gnuplots/documentation"
function test() {
}
function gnp() {
    [ -f settings.gp ] || (echo "no settings.gp file" && return 1) &&
    gnuplot -e "filename='$1'; load 'settings.gp'" $1
}
function h2() {
    cd $REPOS/n3
    [ "$1" ] && [ -z "${1//[0-9]}" ] && nvim $REPOS/n3/pages/ch$1.mdx && return
    case $1 in
        'c') # css
            nvim $REPOS/n3/public/added.css;;
        's')
            nvim $REPOS/n3/public/style.css;;
        'a')
            nvim $REPOS/n3/pages/_app.js;;
        'd')
            nvim $REPOS/n3/pages/_document.js;;
        'p')
            cd $REPOS/n3/pages;;
        'm')
            nvim $REPOS/n3/public/mathjax-config.js;;
        'g')
            cd $REPOS/n3/plots;;
        'n')
            cd $REPOS/n3/node_modules/nextra-theme-docs;;
        'r')
            cd $REPOS/n3 && yarn dev;;
        'v')
            nvim -S ~/.config/nvim/sessions/math;;
        *);;
    esac
}
alias debug="nvim -S ~/.config/nvim/sessions/debug"

# old tikz to svg functions
function ttikz() {
    time (tikz $1)
}
function tikz() {
    x=$1
    if [[ $x =~ ^[0-9]\.[0-9]*$ ]]; then
        x=$(find . -name $x*)
        x=${${x:2}%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    elif [[ $x == *"tex" ]]; then
        x=${x%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    fi
}
