#! /bin/zsh

# ゝ
ARROW="> "

function git_branch_name() {
    branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
    [[ ! -z $branch ]] && echo "[$branch]"
}

setopt prompt_subst

PROMPT=$'%F{blue}%~ %F{241}$(git_branch_name)%f
%(?.%F{green}$ARROW%f.%F{red}$ARROW%f)'
