" setting backup; accessible through ~/.backup directory
set backup
set backupdir=~/.backup

" basic settings
syntax on
set ruler
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set expandtab
set belloff=all

filetype plugin indent on

" plugins
call plug#begin('~/ripples/zsh/vim/plugged')

Plug 'flazz/vim-colorschemes'
Plug 'jremmen/vim-ripgrep'
Plug 'leafgarland/typescript-vim'
Plug 'mbbill/undotree'
Plug 'tomlion/vim-solidity'

call plug#end()

" own configurations
inoremap <Esc> <Esc>`^
set relativenumber
set nu
set nowrap
set smartcase
set incsearch
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey
color molokai
