#! /bin/zsh 

alias vvim="vim"
alias vim="nvim"
alias py="python3"
alias yeet="printf '\033[2J\033[3J\033[1;1H'"
#  -------
# | EDITS |
#  -------
alias vvedit="nvim ~/.vim/vimrc"
alias gedit="nvim ~/.gitconfig"
alias vedit="nvim ~/.config/nvim/init.vim"
alias tedit="nvim ~/.config/kitty/kitty.conf" # t for terminal
alias ttedit="nvim ~/.config/kitty/kitty-themes/themes/Bright_Lights_Khang.conf"
alias pedit="nvim ~/.p10k.zsh"
alias aedit="nvim ~/.config/alacritty/alacritty.yml"
alias ledit="nvim ~/.config/lsd/config.yaml" # ls, ll, la manager
#  ------------
# | DISTILLERY |
#  ------------
alias 2blog="cd ~/Github/blog"
alias 2paper="cd ~/Github/blog/themes/PaperMod/layouts/partials"
alias bedit="nvim ~/Github/blog/config.yml"
alias yedit="nvim ~/Github/blog/.github/workflows/gh-pages.yml"
alias hm="hugo --minify"
#  ----------
# | PERSONAL |
#  ----------
alias diary="cd ~/Desktop/notes && nvim 2021.md"
alias emails="nvim ~/Desktop/notes/emails\ and\ platforms.md"
#  ----------
# | TERMINAL |
#  ----------
alias ls="lsd"
alias la="lsd -a"
alias lst="tree -CL 1 --dirsfirst"
alias lstt="tree -CL 2 --dirsfirst"
alias lsta="tree -CLa 2 --dirsfirst"
alias ll="lsd --long"
alias lla="lsd --long -a"
alias lt="lsd --tree"
alias finder="open ."
#  ------------
# | NAVIGATION |
#  ------------
alias out="cd .."
alias back="cd -"
alias home="cd ~/"

alias 2zsh="cd ~/Documents/Scripts/zsh/config"
alias 2vim="cd ~/.config/nvim"
alias 2qmk="cd ~/Github/qmk_firmware"
alias 2kara="cd ~/.config/karabiner"

alias 2bot="cd ~/Github/trading-bot"
alias 2learn="cd ~/Desktop/learn"
alias 2brew="cd ~/Github/brew-macOS"

alias 2uls="cd /usr/local/scripts"
alias 2dn="cd ~/Desktop/notes"
alias 2ds="cd ~/Documents/Scripts"
alias 2dzf="cd ~/Documents/Scripts/zsh/functions"
#  ------------
# | KEEB / QMK |
#  ------------
alias mk="make dz60:khang"
alias mkd="make dz60:khang:dfu"
alias 2keeb="cd ~/Github/qmk_firmware/keyboards/dz60/keymaps/khang"
alias kedit="cd ~/Github/qmk_firmware && nvim ~/Github/qmk_firmware/keyboards/dz60/keymaps/khang/keymap.c"
#  -----
# | GIT |
#  -----
alias ga="git number add"
alias gaa="git add ."
alias gap="git number add -p"
alias gb="git branch"
alias gc="git commit"
alias gcm="git commit -m"
alias gca="git commit --amend -m"
# delete with ```git branch -d feature```
# delete branch's remote with ```git push origin --delete feature```
alias gco="git number checkout"
# add remote branch with ```git checkout --track origin/feature```
alias gd="git number diff"
alias gr="git number reset"
alias gs="git number"
alias gu="git fetch && git number status" # git update
