#! /bin/zsh 
alias 2math="cd ~/Github/math"
alias 2write="cd ~/Github/math/web/stage-1"
alias 2tex="cd ~/Github/math/web/diagrams/tex"
alias 2dt="cd ~/Desktop/tex_sandbox"
alias write="2write && nvim write.html"
function ttikz() {
    time (tikz $1)
}
function tikz() {
    x=$1
    if [[ $x =~ ^[0-9]\.[0-9]*$ ]]; then
        x=$(find . -name $x*)
        x=${${x:2}%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    elif [[ $x == *"tex" ]]; then
        x=${x%.*}
        echo working on $x ...
        cat packages.tex > output.tex
        cat $x.tex >> output.tex
        ./tikz2svg/tikz2svg output.tex > ../exports/$x.svg
        rm output.tex
        python3 update_dir.py
    fi
}
