#! /bin/zsh

alias diary="cd $REPOS/notes && nvim 2021.md"
alias emails="nvim $REPOS/notes/emails\ and\ platforms.md"

alias t="nvim $REPOS/notes/todo"
alias tt="cat $REPOS/notes/todo"
alias dt="cd $REPOS/notes && git diff $REPOS/notes/todo"
alias gut="cd $REPOS/notes && git add todo && git commit -m 'update' && git push" # git update todo

alias py="python3"
alias snowball="nvim $REPOS/notes/stonks.md"

