#! /bin/zsh

function mountthe() {
    sudo mkdir -p /mnt/$2
    sudo mount $1 /mnt/$2 -o umask=000
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
    cd /mnt/$2
}
function umountthe() {
    sudo umount /mnt/$1
    sudo rmdir /mnt/$1
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
}
function mountexfat() {
    sudo mkdir -p /mnt/$2
    sudo mount -t exfat $1 /mnt/$2
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
    cd /mnt/$2
}
function mountlist() {
    MOUNTED=($(ls /mnt))
    echo ${GREEN}"Mounted drives:"${NORMAL}
    for i in ${MOUNTED[@]}; do
        echo ${RED}"* "${NORMAL}$i
    done
}
