#! /bin/zsh

alias out="cd .."
alias back="cd -"

alias rep="cd $REPOS"

alias 2a="cd $REPOS/arch"
alias 2d="cd $REPOS/dwm"
alias 2n="cd $REPOS/notes"
alias 2k="cd $REPOS/qmk_firmware/keyboards/dz60/keymaps/khang"
alias 2q="cd $REPOS/qmk_firmware"
alias 2v="cd $REPOS/vim"
alias 2z="cd $REPOS/zsh"
