#! /bin/zsh

alias out="cd .."
alias back="cd -"

alias rep="cd $REPOS"

alias 2a="cd $REPOS/arch"
alias 2asc="cd $REPOS/arch/settings/.config"
alias 2b="cd $REPOS/dwmblocks"
alias 2d="cd $REPOS/dwm"
alias 2f="cd $HOME/.local/share/fonts"
alias 2m="cd $REPOS/math/web/stage-1"
alias 2n="cd $REPOS/notes"
alias 2k="cd $REPOS/qmk_firmware/keyboards/dz60/keymaps/khang"
alias 2q="cd $REPOS/qmk_firmware"
alias 2v="cd $REPOS/neovim"
alias 2z="cd $REPOS/zsh"
